apiVersion: v1
kind: Service
metadata:
  name: datadog-app-angular 
  namespace: datadog-app
spec:
  type: ClusterIP
  ports:
    - port: 80  
      targetPort: 80
  selector:
    app: datadog-app-angular