apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-app-angular  
  namespace: datadog-app
  labels:
    app: datadog-app-angular  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-app-angular 
  template:
    metadata:
      labels:
        app: datadog-app-angular 
      annotations:
        ad.datadoghq.com/datadog-app-angular.logs: '[{"source":"nginx","service":"datadog-app-angular"}]'  
    spec:
      containers:
        - name: datadog-app-angular
          image: laols/angular-frontend:latest
          ports:
            - containerPort: 80
          env:
            # Add your Datadog environment variables here if needed
            - name: DD_TRACE_AGENT_URL
              value: 'http://datadog-agent.default:8126'
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_ENABLED
              value: "true"
            - name: DD_DYNAMIC_INSTRUMENTATION_ENABLED
              value: "true"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_ENV
              value: production
            - name: DD_SERVICE
              value: datadog-app-angular  # New service name for Angular
            - name: DD_VERSION
              value: "${VERSION}"