apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-app
      component: backend
  template:
    metadata:
      labels:
        app: datadog-app
        component: backend
      annotations:
        ad.datadoghq.com/datadog-app.logs: '[{"source":"python","service":"datadog-app-backend"}]'
    spec:
      containers:
      - name: flask-app
        image: laols/datadog-app-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DD_TRACE_AGENT_URL
          value: 'http://datadog-agent:8126'
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_TRACE_ENABLED
          value: "true"
        - name: DD_IAST_ENABLED
          value: "true"
        - name: DD_DYNAMIC_INSTRUMENTATION_ENABLED
          value: "true"
        - name: DD_RUNTIME_METRICS_ENABLED
          value: "true"
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_ENV
          value: production
        - name: DD_SERVICE
          value: datadog-app-backend
        - name: DD_VERSION
          value: ""  # Dynamically set in GitHub Actions
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: datadog-app
    component: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP