apiVersion: v1
kind: Service
metadata:
  name: datadog-app-chat
  namespace: datadog-app
  labels:
    app: datadog-app-chat
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5050
  selector:
    app: datadog-app-chat
