apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-app-frontend
  namespace: datadog-app
  labels:
    app: datadog-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-app-frontend
  template:
    metadata:
      labels:
        app: datadog-app-frontend
      annotations:
        ad.datadoghq.com/datadog-app-frontend.logs: '[{"source":"react-native","service":"datadog-app-frontend"}]'
    spec:
      containers:
        - name: datadog-app-frontend
          image: laols/datadog-app-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: DD_TRACE_AGENT_URL
              value: 'http://datadog-agent.default:8126'
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_ENABLED
              value: "true"
            - name: DD_DYNAMIC_INSTRUMENTATION_ENABLED
              value: "true"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_ENV
              value: production
            - name: DD_SERVICE
              value: datadog-app-frontend
            - name: DD_VERSION
              value: "${VERSION}"
