# /k8s/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: datadog-app-frontend
  namespace: datadog-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: datadog-app-frontend