apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-app
      component: frontend
  template:
    metadata:
      labels:
        app: datadog-app
        component: frontend
      annotations:
        ad.datadoghq.com/datadog-app-frontend.logs: '[{"source":"nginx","service":"datadog-app-frontend"}]'
    spec:
      containers:
      - name: datadog-app-frontend  # Ensure this matches your container name
        image: laols/datadog-app-frontend:latest  # Specify the Docker image here
        ports:
        - containerPort: 80
        env:
        - name: DD_ENV
          value: production
        - name: DD_SERVICE
          value: datadog-app-frontend
        - name: DD_VERSION
          value: ""  # This will be updated later with the commit SHA
---
apiVersion: v1
kind: Service
metadata:
  name: datadog-app-frontend-service
spec:
  selector:
    app: datadog-app
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer