apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-app-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-app-nginx
  template:
    metadata:
      labels:
        app: datadog-app-nginx
    spec:
      containers:
      - name: datadog-app-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config