apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-app-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-app-nginx
  template:
    metadata:
      labels:
        app: datadog-app-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Specify your Nginx image here
        ports:
        - containerPort: 80