apiVersion: v1
kind: Service
metadata:
  name: datadog-app-nginx
  namespace: datadog-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: datadog-app-nginx