apiVersion: v1
kind: Service
metadata:
  name: datadog-app-postgres
  namespace: datadog-app
spec:
  type: ClusterIP  
  ports:
    - port: 5432     
      targetPort: 5432 
  selector:
    app: datadog-app-postgres