apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: datadog-app
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
