apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-app-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-app-postgres
  template:
    metadata:
      labels:
        app: datadog-app-postgres
      annotations:
        ad.datadoghq.com/datadog-app-postgres.logs: '[{"source":"postgres","service":"datadog-app-postgres"}]'
    spec:
      spec:
      initContainers:
      - name: init-visitors-table
        image: postgres:latest
        env:
          - name: POSTGRES_USER
            value: "datadog"
          - name: POSTGRES_PASSWORD
            value: "Datadog1!"
          - name: POSTGRES_DB
            value: "datadog-app-db"
        command: ['sh', '-c', 'until pg_isready; do sleep 1; done; psql -U datadog -d datadog-app-db -c "CREATE TABLE IF NOT EXISTS visitors (id SERIAL PRIMARY KEY, visitor_id UUID NOT NULL, visit_time TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, data JSONB);"']
        
      containers:
      - name: datadog-app-postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "datadog"
          - name: POSTGRES_PASSWORD
            value: "Datadog1!"
          - name: POSTGRES_DB
            value: "datadog-app-db"
          - name: DD_VERSION
            value: "default-value"
          - name: DD_ENV
            value: production
          - name: DD_SERVICE
            value: datadog-app-postgres
          - name: DD_RUNTIME_METRICS_ENABLED
            value: "true"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data 
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-data