apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /data/postgres  # Change to your desired path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-app-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-app-postgres
  template:
    metadata:
      labels:
        app: datadog-app-postgres
      annotations:
        ad.datadoghq.com/datadog-app-postgres.logs: '[{"source":"postgres","service":"datadog-app-postgres"}]'
    spec:
      containers:
      - name: datadog-app-postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "datadog"
          - name: POSTGRES_PASSWORD
            value: "Datadog1!"
          - name: POSTGRES_DB
            value: "datadog-app-db"
          - name: DD_VERSION
            value: "default-value"
          - name: DD_ENV
            value: production
          - name: DD_SERVICE
            value: datadog-app-postgres
          - name: DD_RUNTIME_METRICS_ENABLED
            value: "true"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data 
        - name: config-volume
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-data
      - name: config-volume
        configMap:
          name: postgres-config