apiVersion: v1
kind: Service
metadata:
  name: datadog-app-quotes
  namespace: datadog-app
  labels:
    app: datadog-app-quotes
spec:
  type: ClusterIP 
  ports:
    - port: 80 
      targetPort: 5000
  selector:
    app: datadog-app-quotes
    