apiVersion: v1
kind: Service
metadata:
  name: datadog-app-views
  labels:
    app: datadog-app-views
spec:
  type: ClusterIP  # Default type, accessible only within the cluster
  ports:
    - port: 80  # Port for the service
      targetPort: 5000  # Port on the container
  selector:
    app: datadog-app-views