name: Test and deploy backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Set timeout to 5 minutes

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r backend/requirements.txt
        pip install pytest ddtrace

    - name: Run tests with Datadog monitoring
      env:
        DD_CIVISIBILITY_AGENTLESS_ENABLED: true
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_SITE: 'datadoghq.eu'
        DD_ENV: 'ci'
        DD_SERVICE: 'datadog-app-test'
      run: |
        pytest --ddtrace
      continue-on-error: true

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 5  # Set timeout to 5 minutes

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image with Datadog build args
      run: |
        # Get Git repository URL and commit SHA
        REPO_URL=$(git config --get remote.origin.url)
        COMMIT_SHA=$(git rev-parse HEAD)

        # Build Docker image with build arguments
        docker build ./backend \
          -t laols/datadog-app-backend:latest \
          --build-arg DD_GIT_REPOSITORY_URL=${REPO_URL} \
          --build-arg DD_GIT_COMMIT_SHA=${COMMIT_SHA}

        # Push the Docker image
        docker push laols/datadog-app-backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Set timeout to 5 minutes

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy backend to Kubernetes
      run: |
        kubectl apply -f k8s/backend-deployment.yaml

    - name: Set commit SHA for DD_VERSION
      run: |
        # Extract the commit SHA
        VERSION=$(echo ${{ github.sha }} | cut -c1-7)
        # Apply the manifest with a patch to update the DD_VERSION field
        kubectl patch deployment backend -p "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"flask-app\",\"env\":[{\"name\":\"DD_VERSION\",\"value\":\"$VERSION\"}]}]}}}}"

    - name: Mark deployment in Datadog
      run: |
        npx @datadog/datadog-ci deployment mark \
          --env production \
          --service datadog-app-backend \
          --revision "${{ github.sha }}"

    - name: Track deployment in Datadog
      env:
        DD_BETA_COMMANDS_ENABLED: 1
        DD_SITE: 'datadoghq.eu'
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
      run: |
        npx @datadog/datadog-ci dora deployment --service datadog-app-backend --env production \
          --started-at ${{ env.deploy_start }} --finished-at $(date +%s) \
          --git-repository-url "${{ github.event.repository.html_url }}" \
          --git-commit-sha ${{ github.sha }}