name: Build and Deploy Chat Service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/chat/**'
      - 'k8s/chat-deployment.yaml'
      - 'k8s/chat-service.yaml'
      - '.github/workflows/build-and-deploy-chat.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set commit sha for version
        id: set_commit_sha
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-7)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with prebuilt chat app
        run: |
          REPO_URL=$(git config --get remote.origin.url)
          COMMIT_SHA=$(git rev-parse HEAD)
          docker build -f backend/chat/Dockerfile backend/chat/ \
            -t ${{ secrets.DOCKER_USERNAME }}/datadog-app-chat:latest \
            --build-arg DD_GIT_REPOSITORY_URL="$REPO_URL" \
            --build-arg DD_GIT_COMMIT_SHA="$COMMIT_SHA" \
            --build-arg DD_VERSION="$VERSION"

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/datadog-app-chat:latest


  deploy:
    name: Deploy to k8s
    runs-on: ubuntu-latest
    needs: build-and-push
    timeout-minutes: 5

    env:
      DD_BETA_COMMANDS_ENABLED: 1
      DD_GITHUB_JOB_NAME: Deploy to k8s
      DD_SITE: datadoghq.eu
      DD_API_KEY: ${{ secrets.DD_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set commit sha for version
        id: set_commit_sha
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-7)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Tag pipeline in Datadog
        run: npx @datadog/datadog-ci tag --level pipeline --tags team:datadog-app

      - name: Set deployment start time
        id: set_deploy_start
        run: echo "deploy_start=$(date +%s)" >> $GITHUB_ENV

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > ~/.kube/config

      - name: Generate chat deployment with VERSION
        run: |
          export VERSION=$(echo ${{ github.sha }} | cut -c1-7)
          envsubst < k8s/chat-deployment.yaml > k8s/chat-deployment-template.yaml

      - name: Deploy Chat Service to Kubernetes
        run: |
          kubectl apply -f k8s/chat-deployment-template.yaml --insecure-skip-tls-verify
          kubectl apply -f k8s/chat-service.yaml --insecure-skip-tls-verify

      - name: Mark deployment in Datadog
        run: |
          npx @datadog/datadog-ci deployment mark --env production --service datadog-app-chat --revision "${{ github.sha }}"

      - name: Track deployment in Datadog (DORA)
        env:
          DD_BETA_COMMANDS_ENABLED: 1
          DD_SITE: 'datadoghq.eu'
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
        run: |
          npx @datadog/datadog-ci dora deployment \
            --service datadog-app-chat \
            --env production \
            --started-at ${{ env.deploy_start }} \
            --finished-at $(date +%s) \
            --git-repository-url "${{ github.event.repository.html_url }}" \
            --git-commit-sha ${{ github.sha }}
