name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build, Test, and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Set the timeout for the deployment job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        kubectl version --client

    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml  # Add this if you have a service.yaml
