name: Deploy to k8s

on:
  workflow_run:
    workflows: ["Build, Test, and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to k8s
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      DD_BETA_COMMANDS_ENABLED: 1 
      DD_GITHUB_JOB_NAME: Deploy to k8s
      DD_SITE: datadoghq.eu
      DD_API_KEY: ${{ secrets.DD_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set deployment start time
      id: set_deploy_start
      run: echo "deploy_start=$(date +%s)" >> $GITHUB_ENV

    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml --insecure-skip-tls-verify

    - name: Mark deployment in Datadog
      run: |
        npx @datadog/datadog-ci deployment mark \
          --env production \
          --service datadog-app \
          --revision "1.6.3"

    - name: Track deployment in Datadog
      env:
        DD_BETA_COMMANDS_ENABLED: 1
        DD_SITE: 'datadoghq.eu'
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
      run: |
        npx @datadog/datadog-ci dora deployment --service datadog-app --env production \
          --started-at ${{ env.deploy_start }} --finished-at $(date +%s) \
          --git-repository-url "${{ github.event.repository.html_url }}" \
          --git-commit-sha ${{ github.sha }}
        