name: Deploy Nginx to Kubernetes

on:
  push:
    branches:
      - main  # Adjust to your default branch
    paths:
      - 'nginx/**'  # Trigger for changes in the nginx directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Apply ConfigMap
      run: |
        kubectl apply -f datadog-app/nginx/nginx-configmap.yaml --insecure-skip-tls-verify

    - name: Apply Deployment
      run: |
        kubectl apply -f datadog-app/nginx/nginx-deployment.yaml --insecure-skip-tls-verify