name: Test and deploy frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Set timeout to 5 minutes

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js for linting tools
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install HTML and CSS linting tools
      run: |
        npm install -g htmlhint csslint

    - name: Run HTML linting
      run: |
        htmlhint "frontend/**/*.html"

    - name: Run CSS linting
      run: |
        csslint frontend/style.css

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 5  # Set timeout to 5 minutes

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set commit sha for RUM version
      run: |
        # Extract the commit SHA
        VERSION=$(echo ${{ github.sha }} | cut -c1-7)
        # Replace the placeholder VERSION in app.py with the commit SHA
        sed -i "s/version: 'VERSION'/version: '$VERSION'/g" ./frontend/app.js

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build Docker image with Datadog build args
      run: |
        # Get Git repository URL and commit SHA
        REPO_URL=$(git config --get remote.origin.url)
        COMMIT_SHA=$(git rev-parse HEAD)
      
        # Build Docker image with build arguments
        docker build ./frontend \
          -t ${{ secrets.DOCKER_USERNAME }}/datadog-app-frontend:latest \
          --build-arg DD_GIT_REPOSITORY_URL=${REPO_URL} \
          --build-arg DD_GIT_COMMIT_SHA=${COMMIT_SHA}
      
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/datadog-app-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Set timeout to 5 minutes

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy frontend and set DD_VERSION in Kubernetes
      run: |
        # Deploy the frontend application
        kubectl apply -f ./k8s/frontend-deployment.yaml --insecure-skip-tls-verify
      
        # Extract the commit SHA
        VERSION=$(echo ${{ github.sha }} | cut -c1-7)
      
        # Patch the deployment to update the DD_VERSION environment variable
        kubectl patch deployment frontend -p "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"datadog-app-frontend\",\"env\":[{\"name\":\"DD_VERSION\",\"value\":\"$VERSION\"}]}]}}}}" --insecure-skip-tls-verify

    - name: Mark deployment in Datadog
      run: |
        npx @datadog/datadog-ci deployment mark \
          --env production \
          --service datadog-app-frontend \
          --revision "${{ github.sha }}"

    - name: Track deployment in Datadog
      env:
        DD_BETA_COMMANDS_ENABLED: 1
        DD_SITE: 'datadoghq.eu'
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
      run: |
        npx @datadog/datadog-ci dora deployment --service datadog-app-frontend --env production \
          --started-at ${{ env.deploy_start }} --finished-at $(date +%s) \
          --git-repository-url "${{ github.event.repository.html_url }}" \
          --git-commit-sha ${{ github.sha }}